apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: lb4684/user:latest
          name: user
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://sqlsimplsrecka.postgres.database.azure.com:5432/lottery-ticket
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: lukaariana
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lottery-ticket-secret
                  key: password
            - name: EMAIL_VERIFIER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: email-verifier-secret
                  key: api-key
            - name: EMAIL_OTP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: email-otp-secret
                  key: api-key
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 30
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: user
