apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: lb4684/user:latest
          name: user
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://sqlsimplsrecka.postgres.database.azure.com:5432/lottery-ticket
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: lukaariana
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: XonaryLu99
              #valueFrom: #use Kubernetes secret for storing the password
              #  secretKeyRef:
              #    name: #to be added
              #    key: #to be added
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: user
